# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaccard_index_rcpp_parallel <- function(mat1, mat2) {
    .Call('_MSCA_jaccard_index_rcpp_parallel', PACKAGE = 'MSCA', mat1, mat2)
}

rcpp_hello_world <- function() {
    .Call('_MSCA_rcpp_hello_world', PACKAGE = 'MSCA')
}

